# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys, json
from PyQt5 import QtCore, QtGui, QtWidgets

class GUI_Qapp(QtWidgets.QApplication):
    def __init__(self):
        super().__init__(sys.argv)

class GUI_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.show()

    def change(self, value):
        isDict = 0
        if isinstance(value, dict):
            isDict = 1
        if isDict:
            if "type" in value:
                if value["type"] == "subTopics":
                    for i in value["topics"]:
                        self.ui.subTopics.append(i)
                elif value["type"] == "showMsg":
                    botton = QtWidgets.QPushButton("xxx")
                    self.ui.buttonBox.addButton(botton)
                    self.ui.recvPayload.append(json.dumps(json.loads(value["payload"]), sort_keys=True, indent=4, separators=(',', ':')))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.buttonBox = QtWidgets.QButtonGroup(self.centralwidget)
        # self.buttonBox.setGeometry(QtCore.QRect(380, 10, 401, 221))
        self.buttonBox.setObjectName("buttonBox")
        self.recvPayload = QtWidgets.QTextBrowser(self.centralwidget)
        self.recvPayload.setGeometry(QtCore.QRect(380, 240, 401, 321))
        self.recvPayload.setObjectName("recvPayload")
        self.recvPayload.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.recvPayload.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.recvPayload.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.subTopics = QtWidgets.QTextBrowser(self.centralwidget)
        self.subTopics.setGeometry(QtCore.QRect(10, 20, 341, 211))
        self.subTopics.setObjectName("subTopics")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.leftLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setObjectName("leftLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.buttonBox.setTitle(_translate("MainWindow", "buttonBox"))
